[package]
name = "phrack-downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
enum-iterator = "2.3.0"
serde = { version = "1.0.219", features = ["derive"] }
