name: Rust build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build project
        run: cargo build --release
      - name: Run tests
        run: cargo test --all
      - name: Check SPDX headers in Rust files
        run: |
          missing=0
          for file in $(find src -name '*.rs'); do
            if ! grep -q '^// SPDX-License-Identifier: MIT' "$file"; then
              echo "Missing SPDX header in $file"
              missing=1
            fi
          done
          if [ $missing -ne 0 ]; then
            echo "Some files are missing SPDX headers."
            exit 1
          fi
